### ISSUE TITLE
CNAME already exists error on deploy

### ISSUE THREAD

**Issue by petebeegle** [petebeegle/petebeegle.com#6]
Only seem to get this when deploying via github actions 🤷 

```
CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource.
    at Request.extractError (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/runner/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'CNAMEAlreadyExists',
  time: 2021-08-03T19:38:49.683Z,
  requestId: '11556427-da65-47a6-9a72-9a5f7291bc4c',
  statusCode: 409,
  retryable: false,
  retryDelay: 25.749386091763405
}
```

**Comment by petebeegle** [comment]
Workaround here: https://gist.github.com/hadynz/b4e190e0ce10e5811cb462920a9c678f
